#!/usr/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set user [lindex $argv 0];
spawn ./scripts/revoke.sh $user

expect "Enter pass phrase for *"
send -- "password\r"

expect "Enter pass phrase for *"
send -- "password\r"

expect eof
