#!/bin/bash

./hash-password addleness addleness Cardin_pwns
./hash-password analects analects pickerel_symbiosis
./hash-password annalistic annalistic thickets_pimping
./hash-password anthropomorphologically anthropomorphologically likelihoods_hoarsely 
./hash-password blepharosphincterectomy blepharosphincterectomy plagued_teletypewriter 
./hash-password corector corector quadruplet_strawed
./hash-password durwaun durwaun hamlet_laudably
./hash-password dysphasia dysphasia equably_undies
./hash-password encampment encampment Noxzema\'s_wordiness
./hash-password endoscopic endoscopic centennial\'s_subplots
./hash-password exilic exilic service_barbing
./hash-password forfend forfend Tammy\'s_hoofed
./hash-password gorbellied gorbellied pinfeathers_Finnbogadottir\'s
./hash-password gushiness gushiness Cameroon\'s_adaptations
./hash-password muermo muermo grovelling_turtle
./hash-password neckar neckar simmering_Caucasian\'s
./hash-password outmate outmate gush\'s_Colombia
./hash-password outroll outroll carpus\'s_hazardous
./hash-password overrich overrich Freemasonry_bruskest
./hash-password philosophicotheological philosophicotheological lopsided_garishly 
./hash-password pockwood pockwood Borges\'s_helpful
./hash-password polypose polypose lure_leagued
./hash-password refluxed refluxed brushed_volubly
./hash-password reinsure reinsure Hammett_Biden\'s
./hash-password repine repine tallyho\'s_courage
./hash-password scerne scerne fucks_allured
./hash-password starshine starshine soul\'s_blondes
./hash-password unauthoritativeness unauthoritativeness officially_watershed
./hash-password unminced unminced cleaves_refund
./hash-password unrosed unrosed shamed_Dow
./hash-password untranquil untranquil bespoke_supplants
./hash-password urushinic urushinic ramble_tiller\'s
./hash-password vegetocarbonaceous vegetocarbonaceous channelled_inexpressible
./hash-password wamara wamara stirrer_hewer\'s
./hash-password whaledom whaledom petering_sounding\'s
